# fly.toml app configuration file generated for clovers-back on 2023-10-24T16:28:04+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "clovers-back"
primary_region = "arn"

[build]
dockerfile = "./clovers-back/Dockerfile"

[env]
FRONTEND_ADDRESS = "https://clovers.fly.dev"
LISTEN_ADDRESS = "0.0.0.0:8080"
RUST_LOG = "clovers=trace,clovers_back=trace,clovers_svc_common=trace,tower_http=trace"
AWS_DEFAULT_REGION = "eu-central-003"
AWS_REGION = "eu-central-003"
ENDPOINT_URL = "https://s3.eu-central-003.backblazeb2.com"
AWS_ENDPOINT_URL = "https://s3.eu-central-003.backblazeb2.com"
AWS_ENDPOINT_URL_S3 = "https://s3.eu-central-003.backblazeb2.com"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]
