version: "3.9"
services:
  clovers-back:
    restart: always
    build:
      context: .
      dockerfile: ./clovers-back/Dockerfile
    ports:
      - 8080:8080
    environment:
      - POSTGRES_CONNETIONINFO=postgres://postgres:local_development_passphrase@postgres/
      - REDIS_CONNETIONINFO=redis://redis:6379/
      - RUST_LOG=clovers_back=trace,tower_http=trace
      - LISTEN_ADDRESS=0.0.0.0:8080
    depends_on:
      - postgres
      - redis

  clovers-batch:
    restart: always
    build:
      context: .
      dockerfile: ./clovers-batch/Dockerfile
    environment:
      - POSTGRES_CONNETIONINFO=postgres://postgres:local_development_passphrase@postgres/
      - REDIS_CONNETIONINFO=redis://redis:6379/
      - RUST_LOG=clovers_batch=trace,tower_http=trace
      - LISTEN_ADDRESS=0.0.0.0:8080
    depends_on:
      - postgres
      - redis
      - clovers-back

  postgres:
    restart: always
    image: "postgres:14.3"
    expose:
      - 5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=local_development_passphrase

  redis:
    restart: always
    image: "redis:7.0-alpine"
    command: redis-server
    expose:
      - 6379
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data:
