version: "3.9"
services:
  clovers-back:
    restart: always
    build:
      context: .
      dockerfile: ./clovers-back/Dockerfile
    ports:
      - 8080:8080
    environment:
      - REDIS_CONNETIONINFO=redis://redis:6379/
      - RUST_LOG=clovers_back=trace,tower_http=trace
      - LISTEN_ADDRESS=0.0.0.0:8080
    depends_on:
      - redis

  clovers-batch:
    restart: always
    build:
      context: .
      dockerfile: ./clovers-batch/Dockerfile
    environment:
      - REDIS_CONNETIONINFO=redis://redis:6379/
      - RUST_LOG=clovers_batch=trace,tower_http=trace
      - LISTEN_ADDRESS=0.0.0.0:8080
    depends_on:
      - redis
      - clovers-back

  redis:
    restart: always
    image: "redis:7.0-alpine"
    command: redis-server
    expose:
      - 6379
    volumes:
      - redis-data:/data

volumes:
  redis-data:
