# Production-like setup

version: "3.9"
services:
  backend:
    restart: always
    build:
      context: .
      dockerfile: ./clovers-back/Dockerfile
    ports:
      - 8080:8080
    env_file: ./clovers-back/.env
    depends_on:
      - postgres
      - redis

  batch:
    restart: always
    build:
      context: .
      dockerfile: ./clovers-batch/Dockerfile
    env_file: ./clovers-batch/.env
    depends_on:
      - postgres
      - redis # TODO: remove dependency on redis on batch?
      - backend

  preview:
    build:
      context: .
      dockerfile: ./clovers-preview/dev.Dockerfile
    volumes:
      - ./:/app
    command: sh -c "cargo watch -x 'run --release --bin clovers-preview'"
    env_file: ./clovers-preview/.env
    depends_on:
      - redis
      - backend

  frontend:
    build:
      context: ./clovers-front
      dockerfile: Dockerfile
    env_file: ./clovers-front/.env
    ports:
      - 3000:3000

  postgres:
    restart: always
    image: "postgres:14.3"
    expose:
      - 5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=local_development_passphrase

  redis:
    restart: always
    image: "redis:7.0-alpine"
    command: redis-server
    expose:
      - 6379
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data:
