# Local development setup with hot reload on all three services

version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: ./clovers-back/dev.Dockerfile
    volumes:
      - ./:/app
    command: sh -c "cargo watch -x 'run --release --bin clovers-back'"
    ports:
      - 8080:8080
    env_file: ./clovers-back/.env
    depends_on:
      - postgres
      - redis

  batch:
    build:
      context: .
      dockerfile: ./clovers-batch/dev.Dockerfile
    volumes:
      - ./:/app
    command: sh -c "cargo watch -x 'run --release --bin clovers-batch'"
    env_file: ./clovers-batch/.env
    depends_on:
      - postgres
      - redis
      - backend

  preview:
    build:
      context: .
      dockerfile: ./clovers-preview/dev.Dockerfile
    volumes:
      - ./:/app
    command: sh -c "cargo watch -x 'run --release --bin clovers-preview'"
    env_file: ./clovers-preview/.env
    depends_on:
      - redis
      - backend

  frontend:
    build:
      context: ./clovers-front
      dockerfile: dev.Dockerfile
    volumes:
      - ./clovers-front/:/app
    env_file: ./clovers-front/.env
    ports:
      - 3000:3000

  postgres:
    restart: always
    image: "postgres:14.3"
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=local_development_passphrase

  redis:
    restart: always
    image: "redis:7.0-alpine"
    command: redis-server
    expose:
      - 6379
    volumes:
      - redis_data:/data

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:2.3
    ports:
      - "4566:4566" # LocalStack Gateway
    environment:
      - SERVICES=s3:4566
      - DEBUG=${DEBUG-}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"

  createbucket:
    image: amazon/aws-cli:2.13.29
    depends_on:
      - localstack
    volumes:
      - bucket:/aws
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=eu-north-1
    entrypoint: /bin/sh -c
    command: >
      "
        aws --endpoint-url=http://localstack:4566 s3api create-bucket --bucket clovers --region eu-north-1 --create-bucket-configuration LocationConstraint=eu-north-1
      "
volumes:
  pg_data:
  redis_data:
  bucket:
