# Local development setup with hot reload on all three services

version: "3.9"
services:
  backend:
    build:
      context: ./clovers-back/
      dockerfile: dev.Dockerfile
    volumes:
      - ./clovers-back/:/app
    command: sh -c "cargo watch -x 'run --release --bin clovers-back'"
    ports:
      - 8080:8080
    env_file: ./clovers-back/.env
    depends_on:
      - postgres
      - redis

  batch:
    build:
      context: ./clovers-batch/
      dockerfile: dev.Dockerfile
    volumes:
      - ./clovers-batch/:/app
      - ./stl:/app/stl
    command: sh -c "cargo watch -x 'run --release --bin clovers-batch'"
    env_file: ./clovers-batch/.env
    depends_on:
      - postgres
      - redis # TODO: remove dependency on redis on batch?
      - backend

  preview:
    build:
      context: ./clovers-preview/
      dockerfile: dev.Dockerfile
    volumes:
      - ./clovers-preview/:/app
      - ./stl:/app/stl
    command: sh -c "cargo watch -x 'run --release --bin clovers-preview'"
    env_file: ./clovers-preview/.env
    depends_on:
      - redis
      - backend

  frontend:
    build:
      context: ./clovers-front
      dockerfile: dev.Dockerfile
    volumes:
      - ./clovers-front/:/app
    env_file: ./clovers-front/.env
    ports:
      - 3000:3000

  postgres:
    restart: always
    image: "postgres:14.3"
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=local_development_passphrase

  redis:
    restart: always
    image: "redis:7.0-alpine"
    command: redis-server
    expose:
      - 6379
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data:
