name: typescript

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "clovers-front"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: npm install
        run: npm install
      - name: lint
        run: npm run lint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: deploy
        if: ${{ github.event_name == 'push' }}
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
